### PR TITLE
Integration module definitions for TypeScript

### PR DESCRIPTION
**Pull request by goblindegook**
Provides definitions for the `preact` and `react` submodules, should address #57.

### CODE REVIEW

**Comment by ivan-roksandic** [comment]
Hi, it works with functional components but not with Class Components.
Im working on a solution to make interface for the ActionCreator Objects that are returned from the actionmap. That way you can get it recognized within components as well.

**Comment by evenfrost** [comment]
@developit Any chance it will be merged anytime soon? TypeScript in `unistore` is kinda broken atm, I have to use `// @ts-ignore` when importing unistore functions.

**Comment by sammkj** [comment]
The reason `Child` was declared as `any` because of https://github.com/developit/preact/issues/947. For now, you won't be able to type HOC.

**Comment by darky** [comment]
Why it's not merged? It drastically better, than poor types in master branch now.

**Comment by kenfoo** [comment]
Any updates? Still waiting anxiously for a proper typescript definitions for unistore.

**Comment by developit** [comment]
Merging!

**Comment by developit** [comment]
I'm going to publish this as @beta, try it and let me know how it goes

**Pull request merged**
