### PR TITLE
Idea: expose `createAction` as `store.action(action) -> boundAction`

### PR DESCRIPTION
**Pull request by developit**
/cc @cfenzo

### CODE REVIEW

**Comment by developit** [comment]
also pinging @drcmda who is knowledgeable here and might have insight.

**Comment by kadmil** [comment]
Could I ask, is it any different than the current solution? Like, it seems as the same-ish API, so why would you want something like this?

**Comment by developit** [comment]
It just exposes the method, so you can create actions without needing a component first:

```js
import { createStore } from 'unistore'

let store = createStore({ count: 0 })
store.subscribe(console.log)

let increment = store.action( ({ count }) => ({ count: count + 1 }) )

increment()  // logs { count: 1 }
```

**Comment by kadmil** [comment]
Oh, I see. Thanks for explanation, this should be better option indeed.

**Comment by developit** [comment]
Cost of this is 5 bytes. I think we can roll with it, since I shaved a few off prior.

**Pull request merged**
