### PR TITLE
shrink few bytes

### PR DESCRIPTION
**Pull request by pronevich**
Use new Set() in favor of simplify source code and smaller dist size (701 -> 684 as reported in log after build)

### CODE REVIEW

**Comment by developit** [comment]
Set has poor browser support and performance, see this comment:
https://github.com/developit/mitt/pull/8#issuecomment-273372839

**Comment by mellogarrett** [comment]
Could you just write
```
if (listeners[i]===listener) {
  listener = null;
}
else {
  out.push(listeners[i]);
}
```
as
```
if (listeners[i]!==listener) {
  out.push(listeners[i]);
}
```
???

Why is setting it to `null` necessary?

**Comment by pronevich** [comment]
listener = null  will cause GC to remove instantiated listener from memory

**Comment by pronevich** [comment]
@developit  sure, I checked before on browser support, I think it is pretty good (starts from IE 11) but maybe this is not enough :) 

About performance: is it really the case? How many listeners will cause this problem? Maybe more than 10000, but it seems too much for the real case. Also you are on each unsubscribe now 1) create new array "out" 2) iterate over whole array of listeners 3) push from listeners[i] to new array 4) and then listeners = out

With Set here just one step `listeners.delete()`

Also engines become smarter and even now in FF57 I don't see a big difference in Set.prototype.forEach vs Array.prototype.forEach vs for loop

Here https://jsperf.com/object-vs-array-vs-set-vs-map  I see graphs and Set sometimes even faster.

**Comment by developit** [comment]
@mellogarrett @pronevich `listener=null` prevents the loop from finding any additional matches.  If a single listener function reference is added multiple times, `unsubscribe()` should only remove the first.

**Comment by pronevich** [comment]
ah, @developit  thanks for correction on `listener=null`

because IE9+ it makes no sense for PR

**Pull request closed without merging**
