### PR TITLE
Return value (or promise) returned by an action

### PR DESCRIPTION
**Pull request by notpushkin**
Use case:

```js
function LoginView({ login }) {
  return (
    <button onClick={() => {
      login("username", "hackme123")
        .then(() => route("/"));
    }}>Log in!</button>
  );
}

export default connect([], actions)(LoginView);
```

(Not sure if this is the preferred way to do it though!)

### CODE REVIEW

**Comment by developit** [comment]
Hmm - I actually am okay with this I think!

**Comment by tinchoz49** [comment]
this feature can be really helpful!

**Comment by ehinter** [comment]
@developit Any plans to merge this?

**Comment by ehaynes99** [comment]
+1. Especially in the case of the action returning a promise, it would often be much nicer to simply await it rather than having to poison the state tree with some 'loading' value.

**Pull request merged**
