### PR TITLE
Update TypeScript typings

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This brings the typings up to date with the current code in master.

Open tasks:
- ~~[ ] Typesafe integrations~~

**EDIT:** Decided it's better for now to simply fix the `createStore` default export. The integrations seem to be picked up fine by the ts compiler.

### CODE REVIEW

**Comment by developit** [comment]
I think we need additional typings for the dedicated library builds too1

**Comment by jon-grangien** [comment]
Can we merge this?

**Comment by darky** [comment]
Why it's not merged yet? Without this commit, TypeScript broken.

**Comment by developit** [comment]
Sorry all! Not sure how this fell through the cracks.

**Pull request merged**
