### PR TITLE
Fix context types for React build.

### LINKED ISSUE #38: Error: n.getChildContext(): childContextTypes must be defined in order to use getChildContext()
Hi,

I'm trying to use `unistore` to rewrite `react-accessible-accordion` component.
I can't have it to work following the documentation.

I keep getting the following error on my "main" component (Accordion)
`Error: n.getChildContext(): childContextTypes must be defined in order to use getChildContext()`
(cf attached console screenshot)

My code is fairly basic:

```jsx
// @flow

import React, { Component } from 'react';
import type { Node } from 'react';
import { createStore, Provider } from 'unistore/full/react';

type AccordionProps = {
    accordion: boolean,
    children: Node,
    className: string,
    onChange: Function,
    activeItems: Array<string | number>,
};

class Accordion extends Component<AccordionProps, *> {
    static defaultProps = {
        accordion: true,
        onChange: () => {},
        className: 'accordion',
        activeItems: [],
    };

    store = createStore({
        accordion: this.props.accordion,
        onChange: this.props.onChange,
        activeItems: this.props.activeItems,
    });

    render() {
        const { className, accordion, children } = this.props;
        return (
            <Provider store={this.store}>
                <div>Test</div>
            </Provider>
        );
    }
}

export default Accordion;
```

screen shot 2017-12-14 at 2 48 47 pm

### PR DESCRIPTION
**Pull request by developit**
Fixes #38.

### CODE REVIEW

**Comment by srph** [comment]
I apologize if it sounds like I'm rushing, but I was wondering what's keeping this from being merged.

**Comment by vincentaudebert** [comment]
Agree with above that would be great to have these merged and published ASAP

**Comment by vincentaudebert** [comment]
@developit any chance to publish this and #40 soon? Thanks.

**Comment by developit** [comment]
yup

**Pull request merged**
